# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'ding-stall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ding! and Ding! Stall App core functionalities.
  pod 'DingBase', :git => 'git@github.com:cs3217/2018-final-project-group03.git', :branch => 'master'

  # Pods for Firebase-related operations.
  pod 'Firebase/Core'

  # Pods for Firebase-UI functionalities.
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Database'
  pod 'FirebaseUI/Storage'

  # Pods for form input.
  pod 'Eureka'

  # Pods for custom UI button.
  pod 'SwiftyButton'
end
